In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
A = np.mat('[1 2;3 4]')
A

matrix([[1, 2],
        [3, 4]])

In [5]:
b = np.mat('[5 6]')
b

matrix([[5, 6]])

In [6]:
from scipy import linalg

In [9]:
A = np.array([[1,7,5],[2,5,1],[12,3,8]])
linalg.inv(A)

array([[-0.14176245,  0.15708812,  0.06896552],
       [ 0.01532567,  0.19923372, -0.03448276],
       [ 0.20689655, -0.31034483,  0.03448276]])

In [10]:
A.dot(linalg.inv(A))

array([[ 1.00000000e+00, -5.55111512e-17,  4.16333634e-17],
       [ 8.32667268e-17,  1.00000000e+00,  4.16333634e-17],
       [-2.22044605e-16,  4.44089210e-16,  1.00000000e+00]])

In [11]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [12]:
linalg.det(A)

-2.0

In [14]:
import numpy as np
from scipy import linalg
import matplotlib.pyplot as plt
rng = np.random.default_rng()