In [1]:
import numpy as np

In [2]:
a=np.arange(start=2, stop=12, step=2)
print("The Output is :",a)

The Output is : [ 2  4  6  8 10]


In [3]:
a=np.arange(start=2, stop=12)
print("The Output is :",a)

The Output is : [ 2  3  4  5  6  7  8  9 10 11]


In [4]:
a=np.arange(-10, -1)
print("The output is:")
print(a)

The output is:
[-10  -9  -8  -7  -6  -5  -4  -3  -2]


In [6]:
#reshape
a = np.arange(12) 
print("The Original array : \n", a) 

a1= np.arange(12).reshape(2, 6) 
print("\n The reshaped array with 2 rows and 6 columns : \n", a1) 

a2 = np.arange(12).reshape(6,2) 
print("\n The reshaped array with 6 rows and 2 columns : \n", a2) 

a3 = np.arange(12).reshape(2, 3, 2) 
print("\nAfter reshaping the original array to 3D : \n", a3) 

The Original array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 The reshaped array with 2 rows and 6 columns : 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

 The reshaped array with 6 rows and 2 columns : 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

After reshaping the original array to 3D : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [7]:
x = np.arange(12)  
print("The array is :\n",x)
y = np.reshape(x, (4, 3), order='F')  
print("Reshaping the original array using F-like index ordering")
print(y)

The array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaping the original array using F-like index ordering
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [8]:
x = np.arange(12)  
print("The array is :\n",x)
y = np.reshape(x, (4, 3), order='C')  
print("Reshaping the original array using C-like index ordering")
print(y)

The array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaping the original array using C-like index ordering
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
a = np.array([[1, 2, 3], [7, 8, 9]])  
b = np.array([[11, 21, 31], [42, 52, 62]])  
print("The first array:\n",a)
print("The second array:\n",b)
print("The resultant array after appending a & b:")
c = np.append(a,b)  
c  

The first array:
 [[1 2 3]
 [7 8 9]]
The second array:
 [[11 21 31]
 [42 52 62]]
The resultant array after appending a & b:


array([ 1,  2,  3,  7,  8,  9, 11, 21, 31, 42, 52, 62])

In [11]:
a=np.array([[1, 2, 3], [7, 8, 9]])
b=np.array([[11, 21, 31], [42, 52, 62]])
print("The first array:\n",a)
print("The second array:\n",b)
print("The resultant array after appending a & b:")
c=np.append(a,b,axis=0)  
c

The first array:
 [[1 2 3]
 [7 8 9]]
The second array:
 [[11 21 31]
 [42 52 62]]
The resultant array after appending a & b:


array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 21, 31],
       [42, 52, 62]])

In [12]:
a=np.array([[1, 2, 3], [7, 8, 9]])  
b=np.array([[11, 21, 31], [42, 52, 62]])  
print("The first array:\n",a)
print("The second array:\n",b)
print("The resultant array after appending a & b:")
c=np.append(a,b,axis=1)  
c  

The first array:
 [[1 2 3]
 [7 8 9]]
The second array:
 [[11 21 31]
 [42 52 62]]
The resultant array after appending a & b:


array([[ 1,  2,  3, 11, 21, 31],
       [ 7,  8,  9, 42, 52, 62]])

In [13]:
#concatenate()
#numpy.concatenate((a1, a2, ...), axis=0, out=None)
array1 = np.array([[5, 4], [6, 8]])
print("First Array is:\n",array1)
array2 = np.array([[13, 5], [72, 9]])
print("Second Array is :\n",array2)
out= np.concatenate((array1, array2), axis = 0)
print("The result of concatenation is :")
print (out)

First Array is:
 [[5 4]
 [6 8]]
Second Array is :
 [[13  5]
 [72  9]]
The result of concatenation is :
[[ 5  4]
 [ 6  8]
 [13  5]
 [72  9]]


In [14]:
array1 = np.array([[5, 4], [6, 8]])
print("First Array is:\n",array1)
array2 = np.array([[13, 5], [72, 9]])
print("Second Array is :\n",array2)
out= np.concatenate((array1, array2), axis = 1)
print("The result of concatenation is :")
print (out)

First Array is:
 [[5 4]
 [6 8]]
Second Array is :
 [[13  5]
 [72  9]]
The result of concatenation is :
[[ 5  4 13  5]
 [ 6  8 72  9]]


In [16]:
a = np.array([1,4,9])
print("The Array is:")
print(a)

The Array is:
[1 4 9]


In [19]:
import numpy as np
a = np.array([1, 7,9], dtype='complex')
print("The Array with more than one dimension:")
print(a)

The Array with more than one dimension:
[1.+0.j 7.+0.j 9.+0.j]


In [20]:
import numpy as np

a = np.array([[6, 2, 4], [8, 5, 6], [7, 1, 9]])
print("Before Transpose array is :\n",a)
x=np.transpose(a)
print("After Transpose the array is:\n",x)

Before Transpose array is :
 [[6 2 4]
 [8 5 6]
 [7 1 9]]
After Transpose the array is:
 [[6 8 7]
 [2 5 1]
 [4 6 9]]


In [29]:
import numpy as np

inp_ar = np.array([324,2, 0, 1, 5, 4, 9, 78])
print ("The Input array : ")
print(inp_ar)
output = np.partition(inp_ar, 6)
print ("The Output partitioned array : ")
print(output)

The Input array : 
[324   2   0   1   5   4   9  78]
The Output partitioned array : 
[  9   1   0   2   5   4  78 324]


In [32]:
arr = np.array([70, 4, 8, 11, 10, 13])
print("The Input array is :")
print(arr)

output = np.partition(arr, (1, 3))
print("The Output Partitioned array is :")
print(output)

The Input array is :
[70  4  8 11 10 13]
The Output Partitioned array is :
[ 4  8 10 11 70 13]


In [33]:

a = [1.90,2.3,0.6788]
y = np.ceil(a)
print("the output after applying ceil() is:")
print(y)

the output after applying ceil() is:
[2. 3. 1.]


In [34]:
import numpy as np

a = [-1.90,-2.3,-0.6788,12.34]
y = np.ceil(a)
print("the output after applying ceil() is:")
print(y)

the output after applying ceil() is:
[-1. -2. -0. 13.]


In [35]:
a = [0.23,-1.7,1.34,-2.334]
print("The array is :",a)
y = np.floor(a)
print("After applying the floor() method:",y)

The array is : [0.23, -1.7, 1.34, -2.334]
After applying the floor() method: [ 0. -2.  1. -3.]


In [36]:
input_arr = [1.23,0.22,-0.111,-2.555,-3.86,5.0,6.9]
print("The Input array is:")
print(input_arr)
z = np.floor(input_arr)
print("The output array is:")
print(z)

The Input array is:
[1.23, 0.22, -0.111, -2.555, -3.86, 5.0, 6.9]
The output array is:
[ 1.  0. -1. -3. -4.  5.  6.]


In [37]:
x = [1.2,-0.344,5.89]
y = np.trunc(x)
print(y)

[ 1. -0.  5.]


In [38]:
import numpy as np  
  
a = [0.289, 0.089, 1.2, 1.566, 9.909]  
  
print("The Input array is :")  
print(a)
  
y = np.fix(a)  
  
print("The Output array is :")
print(y)

The Input array is :
[0.289, 0.089, 1.2, 1.566, 9.909]
The Output array is :
[0. 0. 1. 1. 9.]


In [39]:
string1 = "this is an apple"
x = np.char.islower(string1)
print("After applying islower() function:")
print(x)

After applying islower() function:
True


In [40]:
inp_ar = np.array(['studytonight', 'Online', 'portal'])

print ("The input array : \n", inp_ar)

output = np.char.islower(inp_ar)
print ("The output array :\n", output)

The input array : 
 ['studytonight' 'Online' 'portal']
The output array :
 [ True False  True]


In [45]:
arr = ['xcccccyyysss', 'AAAAAAAaattttdsxxxxcccc', 'AAaaxxxxcccutt', 'AAaaxxccxcxXDSDdscz'] 
print ("The array is :\n ", arr) 

print ("\nThe find of 'xc'", np.char.find(arr, 'xc')) 
print ("The find of 'xc'", np.char.find(arr, 'xc', start = 3)) 
print ("The find of 'xc'", np.char.find(arr, 'xc', start = 8)) 

The array is :
  ['xcccccyyysss', 'AAAAAAAaattttdsxxxxcccc', 'AAaaxxxxcccutt', 'AAaaxxccxcxXDSDdscz']

The find of 'xc' [ 0 18  7  5]
The find of 'xc' [-1 18  7  5]
The find of 'xc' [-1 18 -1  8]


In [46]:
import numpy as np 

arr = ['AAAabbbbbxcccccyyysss', 'AAAAAAAaattttds', 'AAaaxcutt', 'AAaaxXDSDdscz'] 
print ("The array is :\n ", arr) 

print ("\nThe find of 'xc'", np.char.find(arr, 'xc')) 
print ("The find of 'xc'", np.char.find(arr, 'xc', start = 8)) 

The array is :
  ['AAAabbbbbxcccccyyysss', 'AAAAAAAaattttds', 'AAaaxcutt', 'AAaaxXDSDdscz']

The find of 'xc' [ 9 -1  4 -1]
The find of 'xc' [ 9 -1 -1 -1]


In [47]:
import numpy as np

str1 = np.array(['ooooaaaaqqqk','ccccvvvvvaaaao','ggghhhjjjsskkka'])
print("The original string is:\n",str1)
print("\nThe count of 'a' in str1")

y = np.char.count(str1,'a')
print(y)
print("\nThe count of 'k' in st1:")

z = np.char.count(str1,'k')
print(z)
print("\nThe count of 'o' in st1:")

x = np.char.count(str1,'o')
print(x)

The original string is:
 ['ooooaaaaqqqk' 'ccccvvvvvaaaao' 'ggghhhjjjsskkka']

The count of 'a' in str1
[4 4 1]

The count of 'k' in st1:
[1 0 3]

The count of 'o' in st1:
[4 1 0]


In [48]:
inp1 = np.array(['APPLE', 'Mango', 'guava'])
print ("The input array: ", inp1)
out1 = np.char.istitle(inp1)
print ("The output array:", out1 )

The input array:  ['APPLE' 'Mango' 'guava']
The output array: [False  True False]


In [52]:
inp2 = "This Is An Input String"
print ("The input array : \n", inp2)

out2 = np.char.istitle(inp2)
print ("The output array :\n", out2 )

The input array : 
 This Is An Input String
The output array :
 True


In [53]:
x = np.array(['aAaAaArt', '  aABbV ', 'abBABba'])
print("Input is :", x)

e = np.char.encode(x, encoding='cp500')
print("\nAfter encoding: ", e)

d = np.char.decode(e, encoding='cp500')
print("\nAfter decoding: ", d)

Input is : ['aAaAaArt' '  aABbV ' 'abBABba']

After encoding:  [b'\x81\xc1\x81\xc1\x81\xc1\x99\xa3' b'@@\x81\xc1\xc2\x82\xe5@'
 b'\x81\x82\xc2\xc1\xc2\x82\x81']

After decoding:  ['aAaAaArt' '  aABbV ' 'abBABba']
