In [1]:
import numpy as np

In [2]:
a = np.dot(8, 4) 
print("The dot Product of above given scalar values : ")
print(a) 

# Now we will take 1-D arrays 
vect_a = 4 + 3j
vect_b = 8 + 5j

dot_product = np.dot(vect_a, vect_b) 
print("The Dot Product of two 1-D arrays is : ")
print(dot_product) 

The dot Product of above given scalar values : 
32
The Dot Product of two 1-D arrays is : 
(17+44j)


In [3]:
import numpy as np

a = np.array([[50,100],[12,13]])  
print("The Matrix a is:")
print (a)

b = np.array([[10,20],[12,21]])  
print("The Matrix b is :")
print(b)

dot = np.dot(a,b)  
print("The dot product of a and b is :")
print(dot)

The Matrix a is:
[[ 50 100]
 [ 12  13]]
The Matrix b is :
[[10 20]
 [12 21]]
The dot product of a and b is :
[[1700 3100]
 [ 276  513]]


In [ ]:
#asarray()
