In [1]:
#equal to zero, except for the kth diagonal, whose values are equal to one.
import numpy.matlib  
x = numpy.matlib.eye(n = 4, M = 3, k = 0, dtype = int)
print("The Output is :")
print(x)

The Output is :
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [2]:
  
  
a = numpy.matlib.identity(4)
print("The Identity matrix as output is :")
print(a)

The Identity matrix as output is :
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
a = numpy.matlib.identity(6, dtype = int)
print("The Identity matrix as an output is :")
print(a)

The Identity matrix as an output is :
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [4]:
x = numpy.matlib.rand(4,3)
print("The Random Matrix is :")
print(x)

The Random Matrix is :
[[0.54590115 0.62087592 0.10203069]
 [0.33274129 0.20589643 0.65910168]
 [0.9949402  0.11173582 0.3531989 ]
 [0.56490564 0.75534095 0.41558749]]


In [10]:
#5 x 6 range is 0-1
x = numpy.matlib.rand((5, 6), 4)
print(x)

[[6.41083583e-01 7.87722608e-01 6.14154573e-01 3.57090395e-01
  6.81330647e-01 5.52629401e-01]
 [5.29282633e-01 6.02859344e-01 8.60940684e-01 8.53619643e-01
  4.43436502e-01 1.36783979e-01]
 [9.49864324e-01 4.85199793e-04 8.41019105e-01 6.91786794e-01
  7.09826482e-01 1.46298155e-01]
 [9.24456072e-01 6.07083480e-02 7.71125070e-01 4.16716732e-01
  5.04645624e-01 6.80382181e-01]
 [4.03765118e-02 7.36073201e-01 5.19548986e-01 1.66914994e-01
  5.44839940e-01 6.39707433e-02]]


In [15]:
#返回给定形状的新矩阵，但是不初始化
#numpy.matlib.empty(shape,dtype,order)  
print(numpy.matlib.empty((5,5)))   

[[5.44954407e-321 1.07056472e-311 8.06358401e-313 1.07056473e-311
  1.97626258e-323]
 [1.07056473e-311 1.07056472e-311 1.07056472e-311 1.07056472e-311
  1.07056472e-311]
 [1.06948588e-311 1.07056473e-311 1.06948588e-311 0.00000000e+000
  2.47032823e-323]
 [1.07056473e-311 1.07056472e-311 1.07056472e-311 1.07056472e-311
  1.07056472e-311]
 [1.07056472e-311 2.96439388e-323 1.07056473e-311 1.07056472e-311
  1.07056472e-311]]


In [14]:
print(numpy.matlib.empty((2,3), int))  

[[-2139098208         504 -2111014080]
 [        504           0 -2147483648]]


In [16]:
import numpy as np    
import numpy.matlib    
    
print(numpy.matlib.ones((5,4)))   

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# 1-d array with 5 elements
np.matlib.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [19]:
print("The matrix is:\n",numpy.matlib.zeros((4,3)))  

The matrix is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


The Input  number is: 
40
The Number of bit shift : 
2
After the shifting of 2 bits to left : 
160
