In [2]:
import numpy as np

In [4]:
a = np.array([[2,15,20],[80,43,31],[22,43,10]])  
print("The original array:\n")  
print(a)  

print("\nThe minimum element among the array:",np.amin(a))  
print("\nThe minimum element among the rows of array",np.amin(a,0))  
print("\nThe minimum element among the columns of array",np.amin(a,1)) 

The original array:

[[ 2 15 20]
 [80 43 31]
 [22 43 10]]

The minimum element among the array: 2

The minimum element among the rows of array [ 2 15 10]

The minimum element among the columns of array [ 2 31 10]


In [10]:
arr = [a[...,1],a[...,2]]

In [11]:
print(a[...,1])
print(arr)
print(type(arr))

[15 43 43]
[array([15, 43, 43]), array([20, 31, 10])]
<class 'list'>


In [4]:
a = np.arange(9).reshape((3,3))

print("The Array is :")
print(a)

print("Minimum element in the array is:",np.amin(a))         

print("Minimum element along the first axis of array is:",np.amin(a, axis=0))  

print("Minimum element along the second axis of array is:",np.amin(a, axis=1))

The Array is :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Minimum element in the array is: 0
Minimum element along the first axis of array is: [0 1 2]
Minimum element along the second axis of array is: [0 3 6]


In [1]:
a = np.array([[2,15,20],[80,43,31],[22,43,10]])  
print("The original array:\n")  
print(a)  

print("\nThe maximum element among the array:",np.amax(a))  
print("\nThe maximum element among the rows of array",np.amax(a,0))  
print("\nThe maximum element among the columns of array",np.amax(a,1)) 

NameError: name 'np' is not defined

In [7]:
input_arr = [1, 10, 7, 20, 11, np.nan] 
print("The Input array is : ") 
print(input_arr)
print("The Range of input array is : ")
print(np.ptp(input_arr))

The Input array is : 
[1, 10, 7, 20, 11, nan]
The Range of input array is : 
nan


In [8]:
#ptp =max-min
input_arr = [1, 10, 7, 20,11,56,67] 
print("The Input array is : ") 
print(input_arr)
print("The Range of input array is : ")
print(np.ptp(input_arr))

The Input array is : 
[1, 10, 7, 20, 11, 56, 67]
The Range of input array is : 
66


In [10]:
#平均値
a = [26, 2, 73, 13, 34] 

print("The Input Array is : ") 
print(a)
print("The median of 1D array is : ")
print(np.median(a)) 

The Input Array is : 
[26, 2]
The median of 1D array is : 
14.0


In [11]:
import numpy as np 

#median mid number    
#if num=2 get mean
inp = [[1, 17, 19, 33, 49], [14, 6, 87, 8, 19], [34, 2, 54, 4, 7]] 

print("\nThe median of array when axis = None : ")
print(np.median(inp)) 

# calculating median along the axis = 0 
print("\nThe median of array when axis = 0 : ")
print(np.median(inp, axis = 0)) 

#calculating median along the axis = 1 
print("\nThe median of array when axis = 1 : ")
print(np.median(inp, axis = 1)) 



The median of array when axis = None : 
17.0

The median of array when axis = 0 : 
[14.  6. 54.  8. 19.]

The median of array when axis = 1 : 
[19. 14.  7.]


In [14]:
x= [80, 23, 17, 1, 39] 

print("The Input array is : ")
print(x) 
print("The mean of the array is : ")
print(np.mean(x)) 

The Input array is : 
[80, 23, 17, 1, 39]
The mean of the array is : 
32.0


In [16]:

#std 標準偏差
inp = [22, 2, 17, 11, 34] 

print("The input array is : ")
print(inp)
print("The standard deviation of the Input Array is: ")
print(np.std(inp)) 

print ("\nTo get More precision with float32") 
print("Thus std of array is : ", np.std(inp, dtype = np.float32)) 

print ("\nTo get More accuracy with float64") 
print("The std of array is : ", np.std(inp, dtype = np.float64))

The input array is : 
[22, 2, 17, 11, 34]
The standard deviation of the Input Array is: 
10.721940122944167

To get More precision with float32
Thus std of array is :  10.72194

To get More accuracy with float64
The std of array is :  10.721940122944167


In [15]:

a = np.array([[11, 2], [13, 44]])
print("The array is:\n",a)
print("Standard Deviation is :")
print(np.std(a))

print("Standard Deviation along axis 0:")
print(np.std(a, axis=0))
print("Standard Deviation along axis 1:")
print(np.std(a, axis=1))

The array is:
 [[11  2]
 [13 44]]
Standard Deviation is :
15.850867484147358
Standard Deviation along axis 0:
[ 1. 21.]
Standard Deviation along axis 1:
[ 4.5 15.5]
